---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: instance
    image: centos:7
provisioner:
  name: ansible
  inventory:
    host_vars:
      instance:
        server_cert_name: "master-cert.pem"
        server_key_name: "master-key.pem"
  lint:
    name: ansible-lint
verifier:
  name: testinfra
  lint:
    name: flake8
