---
# Starts docker service
- name: start-docker
  service:
    name: docker
    state: started
    enabled: yes

- name: restart-docker
  service:
    name: docker
    state: restarted

- name: restart-daemon
  systemd:
    daemon_reload: yes