---
# Exiting from previous swarm
- name: Exiting previous swarm
  become: yes
  command: docker swarm leave -f
  failed_when: not "'This node is already part of a swarm' in command_result.stderr"

# Create swarm as manager and advertise it
- name: Setup swarm manager node
  become: yes
  command: docker swarm init --advertise-addr {{ manager_ip }}
  register: swarm_token_output
  ignore_errors: yes

- name: debug
  debug:
    var : swarm_token_output
